fastlane_version "1.21.0"

def import_viadeo_workflow(name, branch='alpha_build')
  import_from_git(
    url: 'git@github.com:viadeo/viadeo-ios-ci-config.git',
    branch: branch,
    path: "#{name}/fastlane/Fastfile"
    )
end

import_viadeo_workflow('ci')
import_viadeo_workflow('app-deployment')
import_viadeo_workflow('tools')
